In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("trending_youtube.csv")

In [3]:
df.shape

(115, 17)

In [5]:
print(df.head(10))

   Unnamed: 0                 channelId              channelTitle  \
0           0  UCU1_l0ZJyTK_7HZZ3Ruw8Dg                      MAPS
1           1  UCLuO2lUqHrPIIpx0hFenV2g            Tink Tink Club
2           2  UCihqrkaOgVMfLNo2W1hSliA              Podcast Bunk
3           3  UCgbWWPn3VYYzxjffZbfj9GQ           Alan Springwind
4           4  UCFmLi6X1mojkFZOFngNR9tQ     Drug Education Agency
5           5  UCxSbJSgLqIO8r7TONBN5dvw  Oracle Frequency Podcast
6           6  UCSqJniChpE6ngCRzUvNNgug       Fabian-ji Chononita
7           7  UCmrLCXSDScliR7q8AxxjvXg       Black Pigeon Speaks
8           8  UC2nzGL6I-SRc_gkBLWLDVWg             ellie pipkins
9           9  UCn8V3KNSgDr1Dai77_y8JrQ          PsychedSubstance

       videoId               publishedAt  \
0  pTnk3ziVVRM  2014-01-10T01:24:57.000Z
1  cuJjSeHZIrg  2015-06-18T16:56:04.000Z
2  IuyuZfWtGgg  2016-05-01T05:33:13.000Z
3  cng_ZhQf8iY  2016-01-25T04:48:22.000Z
4  OpQIQEx7J5A  2014-08-15T10:53:58.000Z
5  U6Ecm1Kb4AI  2015-10-11T06:52:13.000Z
6  qyOW2otR1Vs  2016-05-11T20:24:46.000Z
7  4ekkXrfmPM8  2016-04-23T09:27:30.000Z
8  akZrftACY1I  2016-06-04T12:39:29.000Z
9  UGxSZqTZVaU  2015-09-12T13:44:39.000Z

                                          videoTitle  \
0  Psychedelic Horizons Beyond Psychotherapy Work...
1                     Episode 35 - Dr. James Fadiman
2  #325 Microdosing from The Adam and Dr Drew Sho...
3                Microdosing Away The Same Old Blues
4  Erschossener Kiffer / Drogen in Mikro-Dosierun...
5  Microdosing Psilocybin Mushrooms & LSD - The O...
6  Spagyric Microdosing: An Alchemical Approach t...
7                LSD: Microdosing & the SUPERNATURAL
8                LSD: Microdosing & the SUPERNATURAL
9                 Microdosing LSD or any Psychedelic

                                    videoDescription  videoCategoryId  \
0  Watch the full workshop at http://psychedelics...               29
1  Dr. James Fadiman is the father of modern psyc...               22
2  Adam and Dr. Drew are solo today and they open...               22
3  Source: https://www.spreaker.com/user/springwi...               24
4  Von erschossenen "Dealern", von demonstrierend...               24
5  In recent years, more and more psychedelic exp...               24
6  Spagyric Microdosing: An Alchemical Approach t...               22
7  a http://vidmax.com/ original. If you would li...               25
8  a original. If you would like to support this ...               22
9  How to microdose psychedelics! Everything you ...               28

      videoCategoryLabel    duration  durationSec definition  caption  \
0  Nonprofits & Activism  PT1H19M40S         4780         hd    False
1         People & Blogs  PT1H12M34S         4354         sd    False
2         People & Blogs    PT50M40S         3040         sd    False
3          Entertainment    PT32M21S         1941         hd    False
4          Entertainment    PT26M32S         1592         hd    False
5          Entertainment     PT25M7S         1507         hd    False
6         People & Blogs    PT16M15S          975         hd    False
7        News & Politics    PT13M40S          820         hd    False
8         People & Blogs    PT13M32S          812         hd    False
9   Science & Technology    PT13M25S          805         hd    False

   viewCount  likeCount  dislikeCount  commentCount
0       1512        8.0           0.0           1.0
1        881       14.0           0.0           3.0
2         67        0.0           1.0           3.0
3          4        0.0           0.0           0.0
4       5465      121.0           6.0          25.0
5      12092      136.0           2.0          41.0
6        793       28.0           0.0           3.0
7     108974     4329.0         990.0        3672.0
8          2        0.0           0.0           0.0
9     526243     7046.0         255.0        1706.0

In [6]:
df.describe()

,Unnamed: 0,videoCategoryId,durationSec,viewCount,likeCount,dislikeCount,commentCount
count,115.000000,115.000000,115.000000,115.000000,111.000000,111.000000,113.000000
mean,57.000000,24.417391,402.504348,9164.052174,172.414414,14.207207,77.097345
std,33.341666,4.163295,687.782228,52011.249730,856.646490,97.505722,398.256243
min,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000
25%,28.500000,22.000000,95.000000,128.500000,0.000000,0.000000,0.000000
50%,57.000000,24.000000,220.000000,356.000000,2.000000,0.000000,0.000000
75%,85.500000,28.000000,473.500000,1153.500000,13.000000,1.000000,9.000000
max,114.000000,29.000000,4780.000000,526243.000000,7046.000000,990.000000,3672.000000